"""create Match table

Revision ID: 8c0987e4232f
Revises:
Create Date: 2020-11-09 13:54:46.073807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0987e4232f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('gameId', sa.Integer(), nullable=False),
                    sa.Column('platformId', sa.String(
                        length=40), nullable=False),
                    sa.Column('gameCreation', sa.Integer(), nullable=False),
                    sa.Column('gameDuration', sa.Integer(), nullable=False),
                    sa.Column('queueId', sa.Integer(), nullable=False),
                    sa.Column('seasonId', sa.Integer(), nullable=False),
                    sa.Column('gameMode', sa.String(
                        length=40), nullable=False),
                    sa.Column('teams', sa.JSON(), nullable=False),
                    sa.Column('participants', sa.JSON(), nullable=False),
                    sa.Column('participantIdentities',
                              sa.JSON(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('gameId')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
